### ISSUE TITLE
When PygameUI buttons are pressed part of the background does not change to "active" color

### ISSUE THREAD

**Issue by davidshumway** [Roland00111/Trumpocalypse#16]
Expected behaviour: When pressed the entire background turns to the "active" color.
Actual behaviour: Only the part of the button with a label turns to the "active" color.

**Comment by Roland00111** [comment]
Seems to be fixed

**Comment by davidshumway** [comment]
![screenshot from 2017-05-02 20-48-34](https://cloud.githubusercontent.com/assets/3892695/25645060/d479d74e-2f78-11e7-9f07-9bd742b2442e.png)
