### ISSUE TITLE
Known issue in store

### ISSUE THREAD

**Issue by Roland00111** [Roland00111/Trumpocalypse#4]
Pygame does not error out, however when using the store the game can stop. It has occurred twice while trying to nail down exact causes, but has been difficult to replicate reliably.

Buying and selling items quickly with spam clicking and a large quantity of items.

**Comment by davidshumway** [comment]
Another possibly related issue to this is that sometimes by mashing the Enter key and arrows keys the game errors out. The error message in the shell is:

```Traceback (most recent call last):
  File "Trumpocalypse.py", line 2039, in <module>
    GameState()
  File "Trumpocalypse.py", line 878, in __init__
    self.events_loop = EventsLoop(testevents) # Starts with opening menu.
  File "Trumpocalypse.py", line 276, in __init__
    cm.draw(1) #here is the Menu class function
  File "Trumpocalypse.py", line 118, in draw
    self.PositionSelection %= self.Quanity
AttributeError: StoryScreen instance has no attribute 'Quanity'```
